spring:
  application:
    name: index-codes-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/