eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: index-gather-store-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

