spring:
  application.name: turbine
#它就表示收集 trend-trading-backtest-service 的监控信息了
turbine:
  aggregator:
    clusterConfig: default
  appConfig: trend-trading-backtest-service  ### 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/